# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Subscription Blogging App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Subscription Blogging App

  target 'Subscription Blogging AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Subscription Blogging AppUITests' do
    # Pods for testing
  end

end
